### ISSUE TITLE
2.0.3 is the same as 2.0.2

### ISSUE THREAD

**Issue by Omikorin** [YZarytskyi/react-voice-visualizer#20]
**Describe the bug**
Hi, I've seen the 2.0.3 update. Unfortunately, it didn't change anything due to a missing `npm run build`.
I checked it locally, and it should have the latest updates after building the `dist` folder.

**To Reproduce**
1. Check .js bundle from npm
2. Search for `spinner`

**Expected behavior**
`.spinner` should be visible as `.voice-visualizer__spinner` etc

**Package info (please complete the following information):**
- Version 2.0.3

Thank you

**Comment by YZarytskyi** [comment]
Done. Please, update version to 2.0.4
