### ISSUE TITLE
Property 'onStartAudioPlayback' does not exist on type 'Controls'.

### ISSUE THREAD

**Issue by allison-2** [YZarytskyi/react-voice-visualizer#22]
**Describe the bug**
Try to use the custom hook for my custom play/pause buttons, but it's show the error : Property 'onStartAudioPlayback' does not exist on type 'Controls'.

**To Reproduce**

`import { useVoiceVisualizer, VoiceVisualizer } from 'react-voice-visualizer';
.... other codes
 const recorderControls = useVoiceVisualizer();
 const { setPreloadedAudioBlob, onStartAudioPlayback <-- error here } = recorderControls;`

**Expected behavior**
It should not have error when calling the "on" functions.
**Screenshots**
<img width="968" alt="Screenshot 2024-10-09 at 3 01 32 PM" src="https://github.com/user-attachments/assets/21fdd282-f02a-462a-a28e-e50cb2e7dadd">

**Package info (please complete the following information):**
- Version: ^2.0.4

**Comment by YZarytskyi** [comment]
Hey, onStartAudioPlayback is a parameter of useVoiceVisualizer hook. You can use it like this:
```js
const recorderControls = useVoiceVisualizer({onStartAudioPlayback: () => {} //replace with your callback});
```
