### ISSUE TITLE
Code of demo page

### ISSUE THREAD

**Issue by gemkids275** [YZarytskyi/react-voice-visualizer#3]
Hi sir @YZarytskyi .
I found your package and it's very helpfull.
I also used the [demo page](https://[react-voice-visualizer](https://react-voice-visualizer.vercel.app/).vercel.app/) but couldn't find the example code.
Can you share the example code of above page.
Hope to receive your response soon

**Comment by agarciam14** [comment]
I'd also like to find the example code of that page.

**Comment by YZarytskyi** [comment]
Hi.
Here's the link: [react-audio-visualization](https://github.com/YZarytskyi/react-audio-visualization).

Feel free to explore the examples provided in the repository. If you have any specific questions or need further clarification, please let me know.

**Comment by agarciam14** [comment]
Hi,

Thank you very much.

If I have any questions, I'll let you know

**Comment by gemkids275** [comment]
> Hi. Here's the link: [react-audio-visualization](https://github.com/YZarytskyi/react-audio-visualization).
> 
> Feel free to explore the examples provided in the repository. If you have any specific questions or need further clarification, please let me know.

@YZarytskyi 
Thank you sir very much.
It's very helpful.
Hope I'll see many helpful package from you in the feature.
Have a nice day!
