### ISSUE TITLE
Visualize previous recorded audio

### ISSUE THREAD

**Issue by logicsb** [YZarytskyi/react-voice-visualizer#5]
That's possible to start the component with a previously recorded audio? Something like of by passing a blob by parameter?

Thanks.

**Comment by YZarytskyi** [comment]
Hello there!

At the moment, initiating the component with a previously recorded audio by passing a blob as a parameter is not a supported feature. However, I'll certainly take your suggestion into consideration for potential future updates.

Thank you.

**Comment by pranav-inaira** [comment]
Is this available in this library now?

**Comment by sami-azzam** [comment]
Any updates @YZarytskyi ?
This would be very helpful. Thanks.
